### ISSUE TITLE
DailyShop not working even after outputting a successful startup

### ISSUE THREAD

**Issue by panfriedpanda** [EricLangezaal/DailyShop#1]
I'm running 1.17.1 and DailyShop wont actually work. It passes all of the startup checks and everything but whenever I actually try to add a /dshop it gives an error message in console that reads 'null' and it also outputs an error message in chat.

**Comment by EricLangezaal** [comment]
Can you send me that message in console please (the whole stacktrace)? I tested it on 1.17, but apparently something changed for 1.17.1.

**Comment by panfriedpanda** [comment]
Yes, give me a second

**Comment by panfriedpanda** [comment]
[10:08:42] [Server thread/INFO]: daannte issued server command: /dshop add
[10:08:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dshop' in plugin DailyShop v3.0.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-87]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2165) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1976) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1957) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-87]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at io.github.divios.dailyShop.commands.add.run(add.java:62) ~[?:?]
	at io.github.divios.DailyShop.shaded.Core_lib.commands.CommandManager.lambda$onCommand$1(CommandManager.java:86) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at io.github.divios.DailyShop.shaded.Core_lib.commands.CommandManager.onCommand(CommandManager.java:68) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-87]
	... 21 more

**Comment by EricLangezaal** [comment]
Well, that is not even my plugin 😂. You have gone to the wrong github. As you can see the stacktrace starts with `io.github.divios.dailyshop` even though my plugin is `com.ericdebouwer.dailyshop`. I have been so kind as to look for you, appears you are using https://www.spigotmc.org/resources/daily-shop-random-items-shop-customizable-items-timer-nbt-support-and-more.86907/.

**Comment by panfriedpanda** [comment]
Oh hahah, SO SORRY about that! Thanks for the lightning quick response anyways

**Comment by EricLangezaal** [comment]
No problem and thank you!
